# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3adf1442b0cc828e997783afabbbae5f4852d1e3d48c9ac10fbd326668e05a1d9fa937038720124511ac461811c3419a2c0dcf468f9ded87a562f350ebdca750

test:
  secret_key_base: b1d02283a4c04dfa3aa706d496b024a899abf353effbb99a7d4056ca60a2e637cfc11f07dc3e68a57fe8ba4b8211c275201e1e39177f352254f5005d8bd2c214

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
